### ISSUE TITLE
not able to build the package 

### ISSUE THREAD

**Issue by ibrahim-1811** [Tim-HW/ROS2-PotentialField#2]
fatal error: tf2_geometry_msgs/tf2_geometry_msgs.h: No such file or directory
    3 | #include "tf2_geometry_msgs/tf2_geometry_msgs.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

but i have installed the required package and tried every possible troubleshooting

**Comment by Tim-HW** [comment]
for newer version of ros (humble, jazzy ,...) you have to replace this line with :
```cpp
#include "tf2_geometry_msgs/tf2_geometry_msgs.hpp"
```
Cheers !
